import { test,expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('login, dashboard and dialog have no automated WCAG AA violations',async({page})=>{
 await page.goto('/auth/login');await expect(page.getByRole('heading',{name:'Chào mừng trở lại.'})).toBeVisible();
 let result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();expect(result.violations).toEqual([]);
 await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();await expect(page.getByRole('heading',{name:'An tâm hơn khi luôn có nhau.'})).toBeVisible();
 result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();expect(result.violations).toEqual([]);
 await page.goto('/caregiver/contacts');await page.getByRole('button',{name:'Thêm mới'}).click();await page.getByRole('dialog').getByRole('button',{name:'Lưu thay đổi'}).click();result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();expect(result.violations).toEqual([]);
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Thêm mới'})).toBeFocused();
});
test('registration, password recovery and session logout work without reload',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/auth/register');await page.getByLabel('Địa chỉ email').fill('family-new@demo.vn');await page.getByLabel('Họ và tên').fill('Gia đình mới');await page.getByLabel('Mật khẩu *',{exact:true}).fill('Password@1');await page.getByRole('button',{name:'Tạo tài khoản'}).click();await expect(page.getByRole('heading',{name:/Xin chào/})).toBeVisible();await page.getByRole('button',{name:'Đăng xuất',exact:true}).click();await expect(page.getByRole('heading',{name:'Chào mừng trở lại.'})).toBeVisible();await page.getByRole('link',{name:'Quên mật khẩu?'}).click();await page.getByLabel('Địa chỉ email').fill('family-new@demo.vn');await page.getByRole('button',{name:'Tạo yêu cầu khôi phục'}).click();const message=await page.getByRole('status').innerText();const code=message.match(/DEMO-[a-f0-9]+/)![0];await page.getByRole('link',{name:'Nhập mã khôi phục'}).click();await page.getByLabel('Mã khôi phục demo').fill(code);await page.getByLabel('Mật khẩu mới').fill('Password@2');await page.getByRole('button',{name:'Đặt mật khẩu',exact:true}).click();await expect(page.getByRole('status')).toContainText('Đã đổi mật khẩu');await page.getByRole('link',{name:'Đăng nhập',exact:true}).click();await page.getByLabel('Địa chỉ email').fill('family-new@demo.vn');await page.getByLabel('Mật khẩu *',{exact:true}).fill('Password@2');await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();await expect(page.getByRole('heading',{name:/Xin chào/})).toBeVisible();expect(errors).toEqual([]);
});
