import { Buffer } from 'node:buffer';
import { test,expect,type Page } from '@playwright/test';
async function login(page:Page,email='caregiver@demo.vn'){await page.goto('/auth/login');await page.getByLabel('Địa chỉ email').fill(email);await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();await expect(page.getByRole('heading',{name:/Xin chào/})).toBeVisible();await expect(page.getByRole('heading',{name:/An tâm hơn|Vận hành minh bạch/})).toBeVisible();}
async function screen(page:Page,path:string,title:string){await page.goto(path);await expect(page.getByRole('heading',{name:title,exact:true}).first()).toBeVisible();await expect(page.getByText('Đang tải dữ liệu…',{exact:true})).toHaveCount(0);}
const dialog=(page:Page)=>page.getByRole('dialog').last();
test('caregiver CRUD, validation, alert history and map reconnect',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await login(page);
 await screen(page,'/caregiver/contacts','Liên hệ khẩn cấp');await page.getByRole('button',{name:'Thêm mới',exact:true}).click();await dialog(page).getByLabel('Tên *',{exact:true}).fill('Liên hệ test');await dialog(page).getByLabel('Số điện thoại',{exact:true}).fill('0909999999');await dialog(page).getByRole('button',{name:'Lưu thay đổi'}).click();await expect(dialog(page).getByRole('alert')).toContainText('ưu tiên');await dialog(page).getByLabel('Thứ tự ưu tiên').fill('2');await dialog(page).getByRole('button',{name:'Lưu thay đổi'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('cell',{name:'Liên hệ test',exact:true})).toBeVisible();await page.getByRole('row').filter({hasText:'Liên hệ test'}).getByRole('button',{name:'Xóa',exact:true}).click();await dialog(page).getByRole('button',{name:'Hủy',exact:true}).click();await expect(page.getByRole('cell',{name:'Liên hệ test',exact:true})).toBeVisible();
 await screen(page,'/caregiver/alerts','Trung tâm cảnh báo');await page.getByRole('button',{name:'Xem chi tiết',exact:true}).first().click();await dialog(page).getByRole('button',{name:'Xác nhận hỗ trợ',exact:true}).click();await dialog(page).getByRole('button',{name:'Xác nhận',exact:true}).click();await expect(page.getByRole('dialog').getByText('Chờ hỗ trợ → Đang hỗ trợ',{exact:true})).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Đánh dấu đã giải quyết'}).click();await dialog(page).getByRole('button',{name:'Xác nhận',exact:true}).click();await expect(page.getByRole('dialog').getByText('Đang hỗ trợ → Đã giải quyết',{exact:true})).toBeVisible();
 await screen(page,'/caregiver/map','Bản đồ theo dõi');await page.getByRole('button',{name:'Mô phỏng vị trí cũ',exact:true}).click();await expect(page.getByText('Vị trí cũ — không phải trực tiếp')).toBeVisible();await page.getByRole('button',{name:'Kết nối lại',exact:true}).click();await expect(page.getByText('Đang kết nối lại…',{exact:true})).toBeVisible();await expect(page.getByText('Realtime mô phỏng',{exact:true})).toBeVisible();expect(errors).toEqual([]);
});
test('face upload activation, primary image and delete confirmation',async({page})=>{
 await login(page);await screen(page,'/caregiver/registry','Gương mặt thân quen');await page.getByRole('button',{name:'Quản lý ảnh',exact:true}).click();const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aGZkAAAAASUVORK5CYII=','base64');await dialog(page).getByLabel('Thêm nhiều ảnh JPG/PNG').setInputFiles([1,2,3].map(i=>({name:i+'.png',mimeType:'image/png',buffer:png})));await expect(dialog(page).getByText('Đủ ảnh để nhận diện',{exact:true})).toBeVisible();await expect(dialog(page).getByRole('img')).toHaveCount(3);await dialog(page).getByRole('button',{name:'Đặt ảnh chính',exact:true}).last().click();await expect(dialog(page).getByText('Ảnh chính',{exact:true})).toHaveCount(1);await dialog(page).getByRole('button',{name:'Xóa ảnh',exact:true}).first().click();await dialog(page).getByRole('button',{name:'Xác nhận',exact:true}).click();await expect(page.getByRole('dialog').getByText('Cần ít nhất 3 ảnh',{exact:true})).toBeVisible();
});
test('linked user creation, QR and secondary flags',async({page})=>{
 await login(page);await screen(page,'/caregiver/users','Người được chăm sóc');await page.getByRole('button',{name:'Thêm người thân',exact:true}).click();await dialog(page).getByLabel('Họ và tên').fill('Người dùng thử');await dialog(page).getByLabel('Email').fill('newperson@demo.vn');await dialog(page).getByRole('button',{name:'Lưu thay đổi'}).click();await expect(page.getByRole('cell',{name:'Người dùng thử',exact:true})).toBeVisible();await page.getByRole('button',{name:'Tạo mã QR demo'}).first().click();await expect(dialog(page).locator('svg')).toHaveCount(2);await expect(dialog(page).getByText(/VA-DEMO-/)).toBeVisible();await dialog(page).getByRole('button',{name:'Đóng hộp thoại'}).click();await screen(page,'/caregiver/caregivers','Người chăm sóc phụ');const row=page.getByRole('row').filter({hasText:'Trần Quốc Bảo'});await row.getByRole('button',{name:'Quyền',exact:true}).click();await dialog(page).getByLabel('Quản lý danh bạ khuôn mặt').check();await dialog(page).getByRole('button',{name:'Lưu thay đổi'}).click();await expect(row).toContainText('Registry');
 await page.getByRole('button',{name:'Đăng xuất',exact:true}).click();await login(page,'secondary@demo.vn');await screen(page,'/caregiver/registry','Gương mặt thân quen');await expect(page.getByRole('button',{name:'Thêm mới'})).toBeVisible();await page.goto('/admin/accounts');await expect(page.getByRole('heading',{name:'Không có quyền truy cập'})).toBeVisible();
});
test('center staff, VIU, assignments and org scoping',async({page})=>{
 await login(page,'center@demo.vn');await screen(page,'/center-admin/staff','Nhân viên chăm sóc');await page.getByRole('button',{name:'Thêm tài khoản'}).click();await dialog(page).getByLabel('Họ và tên').fill('Nhân viên mới');await dialog(page).getByLabel('Email').fill('newstaff@demo.vn');await dialog(page).getByRole('button',{name:'Lưu thay đổi'}).click();await expect(page.getByRole('cell').filter({hasText:'Nhân viên mới'})).toBeVisible();await screen(page,'/center-admin/users','Người dùng của trung tâm');await page.getByRole('button',{name:'Thêm tài khoản'}).click();await dialog(page).getByLabel('Họ và tên').fill('Học viên mới');await dialog(page).getByLabel('Email').fill('newstudent@demo.vn');await dialog(page).getByRole('button',{name:'Lưu thay đổi'}).click();await expect(page.getByRole('cell').filter({hasText:'Học viên mới'})).toBeVisible();await screen(page,'/center-admin/assignments','Phân công chăm sóc');await page.getByRole('button',{name:'Thêm liên kết'}).click();await dialog(page).getByLabel('Người chăm sóc *',{exact:true}).selectOption({label:'Nhân viên mới'});await dialog(page).getByLabel('Người khiếm thị *',{exact:true}).selectOption({label:'Học viên mới'});await dialog(page).getByRole('button',{name:'Lưu thay đổi'}).click();await expect(page.getByRole('row').filter({hasText:'Học viên mới'})).toContainText('Nhân viên mới');await screen(page,'/center-admin/map','Bản đồ toàn trung tâm');await expect(page.getByText('Người dùng tổ chức khác')).toHaveCount(0);await page.goto('/caregiver/registry');await expect(page.getByRole('heading',{name:'Không có quyền truy cập'})).toBeVisible();
});
test('admin configuration history rollback and no GPS access',async({page})=>{
 await login(page,'admin@demo.vn');await screen(page,'/admin/configurations','Cấu hình hệ thống');await page.getByRole('row').filter({hasText:'Thời gian chờ té ngã'}).getByRole('button',{name:'Điều chỉnh'}).click();await dialog(page).getByLabel('Giá trị').fill('22');await dialog(page).getByRole('button',{name:'Lưu thay đổi'}).click();await expect(page.getByRole('cell',{name:'15 → 22',exact:true})).toBeVisible();await page.getByRole('button',{name:'Khôi phục giá trị trước'}).click();await dialog(page).getByRole('button',{name:'Xác nhận',exact:true}).click();await expect(page.getByRole('cell',{name:'22 → 15',exact:true})).toBeVisible();await screen(page,'/admin/audit','Nhật ký kiểm toán');await expect(page.getByRole('cell',{name:'Khôi phục cấu hình',exact:true})).toBeVisible();await page.goto('/caregiver/map');await expect(page.getByRole('heading',{name:'Không có quyền truy cập'})).toBeVisible();
});
test('notifications, TTS, geofence and form keyboard focus',async({page})=>{
 await login(page);await screen(page,'/caregiver/notifications','Tùy chọn thông báo');await expect(page.getByLabel('Thông báo đẩy').first()).toBeDisabled();await page.getByRole('button',{name:'Lưu thay đổi'}).first().click();await expect(page.getByRole('status').filter({hasText:'Đã lưu thay đổi'})).toBeVisible();await screen(page,'/caregiver/tts','Giọng đọc hỗ trợ');await page.getByRole('button',{name:'Chỉnh sửa'}).click();await dialog(page).getByLabel('Tốc độ đọc').fill('1.4');await dialog(page).getByRole('button',{name:'Lưu thay đổi'}).click();await expect(page.getByRole('cell').filter({hasText:'1.4'})).toBeVisible();await screen(page,'/caregiver/locations','Địa điểm quen thuộc');await page.getByRole('button',{name:'Vùng an toàn',exact:true}).click();await page.getByRole('button',{name:'Thêm mới'}).click();await dialog(page).getByRole('button',{name:'Lưu thay đổi'}).click();await expect(dialog(page).getByLabel('Tên *',{exact:true})).toBeFocused();await dialog(page).getByLabel('Tên *',{exact:true}).fill('Vùng thử');await dialog(page).getByLabel('Bán kính (m)').fill('-1');await dialog(page).getByRole('button',{name:'Lưu thay đổi'}).click();await expect(dialog(page).getByText('Giá trị tối thiểu 1.')).toBeVisible();await dialog(page).getByLabel('Bán kính (m)').fill('100');await dialog(page).getByRole('button',{name:'Lưu thay đổi'}).click();await expect(page.getByRole('cell',{name:'Vùng thử',exact:true})).toBeVisible();
});
test('every role route renders on tablet without console errors or document overflow',async({page})=>{
 await page.setViewportSize({width:1024,height:900});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));for(const [email,paths] of [['caregiver@demo.vn',['users','map','alerts','registry','locations','contacts','caregivers','activity','tts','notifications']],['center@demo.vn',['organization','staff','users','assignments','map','reports','routing']],['admin@demo.vn',['organizations','accounts','links','metrics','configurations','rules','delivery','audit']]] as [string,string[]][]){await login(page,email);const base=email.startsWith('center')?'center-admin':email.startsWith('admin')?'admin':'caregiver';for(const path of paths){await page.goto('/'+base+'/'+path);await expect(page.locator('main h1')).toBeVisible();await expect(page.getByText('Đang tải dữ liệu…',{exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),path+' overflow').toBe(true);await expect(page.getByRole('alert')).toHaveCount(0);}await page.getByRole('button',{name:'Đăng xuất',exact:true}).click();}expect(errors).toEqual([]);
});
test('narrow view navigation and reset demo',async({page})=>{await page.setViewportSize({width:390,height:844});await login(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Mở điều hướng'}).click();await page.getByRole('link',{name:'Người được chăm sóc',exact:true}).click();await expect(page.getByRole('heading',{name:'Người được chăm sóc',exact:true}).first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Reset dữ liệu demo'}).click();await dialog(page).getByRole('button',{name:'Xác nhận',exact:true}).click();await expect(page.getByRole('heading',{name:'Chào mừng trở lại.'})).toBeVisible();});

