import { useState, useEffect } from 'react';
import { BrowserRouter, Routes, Route, Navigate, NavLink, Outlet, Link } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { LogOut, Menu, LayoutDashboard, UserRound, ShieldCheck } from 'lucide-react';
import { useAuth, useSession, useSnapshot } from '../hooks/useService';
import { Brand, Confirm, PageHead, State } from '../components/UI';
import { AuthPage } from '../pages/auth/AuthPage';
import { Profile } from '../pages/shared/Profile';
import { roles } from '../constants/labels';
import { uiStore, useUI } from '../stores/ui';
export const queryClient=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});
export function Guard({role}:{role?:string}){const q=useSession();if(q.isPending)return <div className="empty" role="status">Đang kiểm tra phiên…</div>;if(q.isError)return <div className="main"><State error={q.error} retry={()=>q.refetch()}><span/></State><Link to="/auth/login">Đăng nhập</Link></div>;if(!q.data)return <Navigate to="/auth/login" replace/>;if(q.data.role==='VisuallyImpaired'||role&&q.data.role!==role)return <Navigate to="/forbidden" replace/>;return <Outlet/>;}
export const roleBase=(role:string)=>role==='Caregiver'?'/caregiver':role==='CenterAdmin'?'/center-admin':'/admin';
export const menu:Record<string,{path:string;label:string}[]>={Caregiver:[],CenterAdmin:[],Admin:[]};
function Shell(){const {data:user}=useSession();const auth=useAuth();const [open,setOpen]=useState(false);const [reset,setReset]=useState(false);const {notice}=useUI();useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>uiStore.set({notice:''}),5000);return()=>clearTimeout(timer);},[notice]);if(!user)return null;return <div className="shell"><a className="skip" href="#main">Đến nội dung chính</a><aside className={'sidebar'+(open?' open':'')}><Brand/><div><p className="eyebrow" style={{padding:'0 12px 12px'}}>Không gian của bạn</p><nav className="nav" aria-label="Điều hướng chính"><NavLink to="/" end onClick={()=>setOpen(false)}><LayoutDashboard size={18}/>Tổng quan</NavLink>{menu[user.role]?.map(item=><NavLink key={item.path} to={roleBase(user.role)+'/'+item.path} onClick={()=>setOpen(false)}><span aria-hidden="true">◦</span>{item.label}</NavLink>)}</nav></div><div className="sidebar-foot stack"><div className="notice"><ShieldCheck size={20}/><p>Mỗi kết nối là một sự an tâm.</p></div><nav className="nav"><NavLink to="/profile"><UserRound size={18}/>Hồ sơ của tôi</NavLink></nav><button className="btn" onClick={()=>auth.logout()}><LogOut size={16}/>Đăng xuất</button></div></aside><div className="workspace"><header className="topbar"><div className="row"><button className="btn mobile-menu" aria-label="Mở điều hướng" aria-expanded={open} onClick={()=>setOpen(!open)}><Menu size={18}/></button><span className="muted" style={{fontSize:13}}>VisionAid <span aria-hidden="true">/</span> {roles[user.role]}</span></div><Link className="row" to="/profile"><span className="avatar">{user.name.split(' ').at(-1)?.slice(0,2).toUpperCase()}</span><span style={{fontSize:13,color:'var(--text)'}}><strong>{user.name}</strong><br/><small>{roles[user.role]}</small></span></Link></header>{auth.mode==='mock'&&<div className="demo-strip"><span>● Chế độ demo · Dữ liệu mô phỏng, chưa kết nối backend</span><button style={{border:0,background:'transparent',color:'var(--primary)',textDecoration:'underline'}} onClick={()=>setReset(true)}>Reset dữ liệu demo</button></div>}<main id="main" tabIndex={-1} className="main"><Outlet/></main></div>{notice&&<div role="status" className="toast">{notice}</div>}{reset&&<Confirm title="Reset dữ liệu demo?" description="Xóa toàn bộ thay đổi, ảnh demo và phiên đăng nhập trên trình duyệt này để trở về dữ liệu mẫu." onClose={()=>setReset(false)} onConfirm={auth.resetDemo}/>}</div>;}
function Home(){const q=useSnapshot();const {data:user}=useSession();return <><PageHead title={`Xin chào, ${user?.name.split(' ').at(-1)} 👋`} description="Cùng bạn theo dõi và chăm sóc những điều quan trọng."/><State loading={q.isPending} error={q.error} retry={()=>q.refetch()}><div className="grid">{[['Người trong phạm vi',q.data?.people.length],['Liên kết chăm sóc',q.data?.links.length],['Cảnh báo cần hỗ trợ',q.data?.alerts.filter(a=>['SENT','ESCALATED'].includes(a.status)).length]].map(([label,value])=><section className="glass card stack" key={label}><span className="muted">{label}</span><strong className="stat">{value??0}</strong><span className="badge blue">Dữ liệu demo</span></section>)}</div></State></>;}
export function App(){return <QueryClientProvider client={queryClient}><BrowserRouter><Routes><Route path="/auth/:action" element={<AuthPage/>}/><Route element={<Guard/>}><Route element={<Shell/>}><Route index element={<Home/>}/><Route path="profile" element={<Profile/>}/><Route path="forbidden" element={<><PageHead title="Không có quyền truy cập" description="Tài khoản của bạn không được cấp quyền cho màn hình này."/><Link className="btn" to="/">Về tổng quan</Link></>}/><Route path="*" element={<><PageHead title="Không tìm thấy trang" description="Đường dẫn không tồn tại hoặc đã được thay đổi."/><Link className="btn" to="/">Về tổng quan</Link></>}/></Route></Route></Routes></BrowserRouter></QueryClientProvider>;}
